import { askCopilot } from '../core/copilot.js';
import { OutputManager } from '../core/output-manager.js';
import { PromptContext } from '../core/prompt-builder.js';
import { Progress } from '../core/progress.js';
import { GitAnalysis } from '../scanners/git-analyzer.js';
import {
  prTemplatePrompt, bugReportPrompt, featureRequestPrompt,
  codeReviewChecklistPrompt, onboardingPrompt, developmentWorkflowPrompt,
} from '../prompts/team.prompts.js';

export interface TeamEngineInput {
  context: PromptContext;
  gitAnalysis: GitAnalysis;
  hasPRTemplate: boolean;
  hasIssueTemplates: boolean;
  hasCodeowners: boolean;
}

export async function runTeamEngine(
  input: TeamEngineInput,
  output: OutputManager,
  progress: Progress,
): Promise<{ score: number; details: string }> {
  progress.start('Team Engine', 7);

  const ctx = { ...input.context };
  if (input.gitAnalysis.contributors.length > 0) {
    ctx.additionalContext = (ctx.additionalContext || '') +
      `\nContributors:\n${input.gitAnalysis.contributors.map(c => `${c.name} (${c.commits} commits)`).join('\n')}`;
  }

  // PR Template
  progress.increment('PR template');
  const prResult = await askCopilot(prTemplatePrompt(ctx));
  await output.writeToSubdir('team', 'PULL_REQUEST_TEMPLATE.md', prResult);

  // Bug report template
  progress.increment('Bug report template');
  const bugResult = await askCopilot(bugReportPrompt(ctx));
  await output.writeToSubdir('team/ISSUE_TEMPLATE', 'bug_report.md', bugResult);

  // Feature request template
  progress.increment('Feature request template');
  const featureResult = await askCopilot(featureRequestPrompt(ctx));
  await output.writeToSubdir('team/ISSUE_TEMPLATE', 'feature_request.md', featureResult);

  // Issue template config
  progress.increment('Issue template config');
  const configYml = `blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: ./README.md
    about: Check the documentation before filing an issue
`;
  await output.writeToSubdir('team/ISSUE_TEMPLATE', 'config.yml', configYml);

  // CODEOWNERS
  progress.increment('CODEOWNERS');
  const codeownersLines: string[] = ['# Auto-generated by RepoSentry', ''];
  for (const [dir, owner] of input.gitAnalysis.directoryOwnership) {
    codeownersLines.push(`/${dir}/ @${owner.replace(/\s+/g, '-').toLowerCase()}`);
  }
  if (codeownersLines.length <= 2) {
    codeownersLines.push('* @' + (input.gitAnalysis.contributors[0]?.name.replace(/\s+/g, '-').toLowerCase() || 'owner'));
  }
  await output.writeToSubdir('team', 'CODEOWNERS', codeownersLines.join('\n'));

  // Code review checklist
  progress.increment('Code review checklist');
  const reviewResult = await askCopilot(codeReviewChecklistPrompt(ctx));
  await output.writeToSubdir('team', 'CODE_REVIEW_CHECKLIST.md', reviewResult);

  // Onboarding + workflow
  progress.increment('Onboarding guide');
  const onboardResult = await askCopilot(onboardingPrompt(ctx));
  await output.writeToSubdir('team', 'ONBOARDING.md', onboardResult);

  const workflowResult = await askCopilot(developmentWorkflowPrompt(ctx));
  await output.writeToSubdir('team', 'DEVELOPMENT_WORKFLOW.md', workflowResult);

  progress.succeed('Team Engine');

  // Score based on what the project already has (not what we generated)
  let score = 15; // base
  if (input.hasPRTemplate) score += 25;
  if (input.hasIssueTemplates) score += 20;
  if (input.hasCodeowners) score += 20;
  if (input.gitAnalysis.contributors.length > 1) score += 10; // multi-contributor
  if (input.gitAnalysis.contributors.length > 3) score += 10; // active team

  const missing: string[] = [];
  if (!input.hasPRTemplate) missing.push('PR template');
  if (!input.hasIssueTemplates) missing.push('issue templates');
  if (!input.hasCodeowners) missing.push('CODEOWNERS');

  score = Math.max(0, Math.min(100, score));

  return {
    score,
    details: missing.length > 0 ? `Missing: ${missing.join(', ')} | ${input.gitAnalysis.contributors.length} contributors` : `All collaboration files present | ${input.gitAnalysis.contributors.length} contributors`,
  };
}
